# Generated by Django 3.1.7 on 2021-03-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidStaticReport',
            fields=[
                ('ANALYZER', models.CharField(default='', max_length=50)),
                ('SIZE', models.CharField(default='', max_length=50)),
                ('MD5', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('MAIN_ACTIVITY', models.TextField(default='')),
                ('EXPORTED_ACTIVITIES', models.TextField(default='')),
                ('BROWSABLE_ACTIVITIES', models.TextField(default={})),
                ('ACTIVITIES', models.TextField(default=[])),
                ('RECEIVERS', models.TextField(default=[])),
                ('PROVIDERS', models.TextField(default=[])),
                ('SERVICES', models.TextField(default=[])),
                ('LIBRARIES', models.TextField(default=[])),
                ('TARGET_SDK', models.CharField(default='', max_length=50)),
                ('MAX_SDK', models.CharField(default='', max_length=50)),
                ('MIN_SDK', models.CharField(default='', max_length=50)),
                ('VERSION_NAME', models.CharField(default='', max_length=100)),
                ('VERSION_CODE', models.CharField(default='', max_length=50)),
                ('ICON_HIDDEN', models.BooleanField(default=False)),
                ('ICON_FOUND', models.BooleanField(default=False)),
                ('PERMISSIONS', models.TextField(default={})),
                ('CERTIFICATE_ANALYSIS', models.TextField(default={})),
                ('MANIFEST_ANALYSIS', models.TextField(default=[])),
                ('BINARY_ANALYSIS', models.TextField(default=[])),
                ('FILE_ANALYSIS', models.TextField(default=[])),
                ('ANDROID_API', models.TextField(default={})),
                ('CODE_ANALYSIS', models.TextField(default={})),
                ('NIAP_ANALYSIS', models.TextField(default={})),
                ('URLS', models.TextField(default=[])),
                ('DOMAINS', models.TextField(default={})),
                ('EMAILS', models.TextField(default=[])),
                ('STRINGS', models.TextField(default=[])),
                ('FIREBASE_URLS', models.TextField(default=[])),
                ('FILES', models.TextField(default=[])),
                ('EXPORTED_COUNT', models.TextField(default={})),
                ('APKID', models.TextField(default={})),
                ('TRACKERS', models.TextField(default={})),
                ('PLAYSTORE_DETAILS', models.TextField(default={})),
                ('NETWORK_SECURITY', models.TextField(default=[])),
                ('SECRETS', models.TextField(default=[])),
            ],
        ),
    ]
