# Generated by Django 3.1.7 on 2021-03-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0004_auto_20210330_2140'),
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AndroidStaticReport',
        ),
    ]
