# Generated by Django 3.1.7 on 2021-05-04 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JavaResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANALYZER', models.CharField(default='', max_length=50)),
                ('SCAN_TYPE', models.CharField(default='', max_length=10)),
                ('FILE_NAME', models.CharField(default='', max_length=260)),
                ('MD5', models.CharField(default='', max_length=32)),
                ('TIMESTAMP', models.DateTimeField(default=datetime.datetime.now)),
                ('ANALYSIS_RESULT', models.TextField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='RecentScansDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANALYZER', models.CharField(default='', max_length=50)),
                ('SCAN_TYPE', models.CharField(default='', max_length=10)),
                ('FILE_NAME', models.CharField(default='', max_length=260)),
                ('APP_NAME', models.CharField(default='', max_length=260)),
                ('PACKAGE_NAME', models.CharField(default='', max_length=260)),
                ('VERSION_NAME', models.CharField(default='', max_length=50)),
                ('MD5', models.CharField(default='', max_length=32)),
                ('TIMESTAMP', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StaticAnalyzerAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILE_NAME', models.CharField(default='', max_length=260)),
                ('APP_NAME', models.CharField(default='', max_length=255)),
                ('APP_TYPE', models.CharField(default='', max_length=20)),
                ('SIZE', models.CharField(default='', max_length=50)),
                ('MD5', models.CharField(default='', max_length=32)),
                ('PACKAGE_NAME', models.TextField(default='')),
                ('MAIN_ACTIVITY', models.TextField(default='')),
                ('EXPORTED_ACTIVITIES', models.TextField(default='')),
                ('BROWSABLE_ACTIVITIES', models.TextField(default={})),
                ('ACTIVITIES', models.TextField(default=[])),
                ('RECEIVERS', models.TextField(default=[])),
                ('PROVIDERS', models.TextField(default=[])),
                ('SERVICES', models.TextField(default=[])),
                ('LIBRARIES', models.TextField(default=[])),
                ('TARGET_SDK', models.CharField(default='', max_length=50)),
                ('MAX_SDK', models.CharField(default='', max_length=50)),
                ('MIN_SDK', models.CharField(default='', max_length=50)),
                ('VERSION_NAME', models.CharField(default='', max_length=100)),
                ('VERSION_CODE', models.CharField(default='', max_length=50)),
                ('PERMISSIONS', models.TextField(default={})),
                ('MANIFEST_ANALYSIS', models.TextField(default=[])),
                ('CODE_ANALYSIS', models.TextField(default={})),
                ('EMAILS', models.TextField(default=[])),
                ('URLS', models.TextField(default=[])),
                ('EXPORTED_COUNT', models.TextField(default={})),
                ('NETWORK_SECURITY', models.TextField(default=[])),
                ('FLOW_REPORT', models.TextField(default=[])),
                ('DYNAMIC_REPORT', models.TextField(default={})),
            ],
        ),
    ]
