# Generated by Django 3.1.7 on 2021-04-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0004_auto_20210330_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='APKID',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='CERTIFICATE_ANALYSIS',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='EMAILS',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='FILES',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='PLAYSTORE_DETAILS',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='SECRETS',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='SHA1',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='SHA256',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='TRACKERS',
        ),
    ]
