# Generated by Django 3.1.7 on 2021-04-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0005_auto_20210405_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='BINARY_ANALYSIS',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='STRINGS',
        ),
    ]
