# Generated by Django 3.1.7 on 2021-04-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0007_auto_20210405_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='ANDROID_API',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='NIAP_ANALYSIS',
        ),
    ]
