# Generated by Django 3.1.7 on 2021-04-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0008_auto_20210411_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='ICON_FOUND',
        ),
        migrations.RemoveField(
            model_name='staticanalyzerandroid',
            name='ICON_HIDDEN',
        ),
    ]
